name: finerit_app_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  webview_flutter: ^0.3.3+1
  image_picker_saver: ^0.1.0
  flutter_webview_plugin: ^0.3.0+2
  json_annotation: 2.0.0
  lpinyin: 1.0.6  #latest version
#  chewie: 0.8.0
  zefyr: ^0.3.0
  flutter_spinkit: "^3.1.0"
  async: ^2.0.8
  flutter_easyrefresh: ^1.0.7
  cached_network_image: ^0.5.0
  url_launcher: 4.0.3
  multi_image_picker: ^2.4.11
  amap_location:
  dio: 1.0.13
  fluttertoast:
  shared_preferences: ^0.4.3
  sqflite: any
  jaguar_orm: ^2.2.0
  jaguar_query_sqflite: ^2.2.0
  path: ^1.6.2
  simple_permissions:
  easy_alert:
  camera: 0.2.9+1
  scoped_model:
  progress_indicators: ^0.1.2
  path_provider:
  advanced_share:
  giffy_dialog:
  audio_recorder:
  flutter_slidable:
  audioplayer:
  video_player: 0.7.2
  open_iconic_flutter: 0.3.0
  rflutter_alert: ^1.0.2
  pimp_my_button:
      git:
        url: git://github.com/Norbert515/pimp_my_button.git
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  json_serializable: 2.0.1
  build_runner: 1.1.3
  jaguar_orm_gen: ^2.2.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
#    - family: MyFlutterApp2
#      fonts:
#        -asset: fonts/icons_new2.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/icons_new.ttf

    - family: MyFlutterApp2
      fonts:
        - asset: fonts/icons_new2.ttf

    - family: MyFlutterApp3
      fonts:
        - asset: fonts/icons_new3.ttf

    - family: MyFlutterApp4
      fonts:
        - asset: fonts/icons_new4.ttf




  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/data/contacts.json
  - assets/course/erya.png
  - assets/course/shuake2.png
  - assets/course/souti.png
  - assets/course/zhidao.png
  - assets/course/zhihuishu.png
  - assets/course/xuexitong.png
  - assets/base/finer.png
  - assets/base/left.png
  - assets/base/right.png
  - assets/base/head.png
  - assets/base/sad.jpg
  - assets/base/informationbg.png
  - assets/base/informationbg.jpg
  - assets/base/informationbg.jpeg
  - assets/loading.png
  - assets/profile/verify/back_id_card.png
  - assets/profile/verify/front_id_card.png
  - assets/profile/verify/inside_student_card.png
  - assets/profile/verify/outside_student_card.png
  - assets/space_demo.flr
  - assets/sorry.gif
  - assets/smile.png
  - assets/great_comment_award.png
  - assets/award_money.png
  - assets/after_second.png
  - assets/second_award.png
  - assets/third_award.png
  - assets/top_award.png
  - assets/task.png
  - assets/ranking.png
  - assets/award_box.png
  - assets/open_box.gif
  - assets/profile/task/comment.png
  - assets/profile/task/god_comment.png
  - assets/profile/task/invite.png
  - assets/profile/task/moments.png
  - assets/profile/task/popup.png
  - assets/profile/task/post.png
  - assets/profile/task/qzone.png
  - assets/profile/task/ranking.png
  - assets/profile/task/verify.png
  - assets/course/splash_bg.png
  - assets/welcome/cover1.png
  - assets/welcome/cover2.png
  - assets/fire.png
  - assets/fire2.png
  - assets/nodata.png
  - assets/sousuoying.jpg
  - assets/course.png
  - assets/backimg.jpeg
  - assets/weibo.png
  - assets/studentinside.png
  - assets/studentoutside.png
  - assets/idcardinside.png
  - assets/idcardourside.png
  - assets/voice.png
  - assets/backimg.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
