/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData alter = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData addressbook = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData comment2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData article = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData create2 = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData createt = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData godcomments = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData identity = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData like2 = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData look = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData mine = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData money2 = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData more = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData newtask = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData next = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData photo = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData playnext = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData rank = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData return_icon = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData wallet = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData wallet2 = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData winning_course = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData write = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData addfriend = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData playnext_onclick = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData addressbook_onclick = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData house_onclick = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData message_onclick = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData mine_onclick = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData eyeclose = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData eyes = const IconData(0xe84b, fontFamily: _kFontFam);
}
