/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp4 {
  MyFlutterApp4._();

  static const _kFontFam = 'MyFlutterApp4';

  static const IconData like3 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData look = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData mine = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData newtask = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData notauth = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData pen = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData playlast = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData playnext = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData rank = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData right = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData school = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData unlock = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData up = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData voice = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData wallet2 = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData winning_course = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData write = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData addfriend = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData address = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData addressbook = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData alter = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData alteruser = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData article = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData auth = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData bofang = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData comment2 = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData create = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData create2 = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData down = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData eyeclose = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData eyes = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData fail = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData false_icon = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData feedback = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData godcomments = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData image = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData iphone = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData jianpan = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData left = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData like2 = const IconData(0xe83a, fontFamily: _kFontFam);
}
